version: '3.8'

services:
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pods
      MYSQL_USER: lambda_pods
      MYSQL_PASSWORD: lambda_pods
    volumes:
      - .voluems/mysql_data:/var/lib/mysql
